name: Deploy GKE

on:
  workflow_dispatch:
    inputs:
      gke-cluster:
        required: true
        type: string
  # This is reusable workflow - providing full GKE deploy
  workflow_call:
    inputs:
      gke-cluster:
        required: true
        type: string

jobs:
  setup:
    uses: ./.github/workflows/setup_gke_sa-sample.yml
    with: 
      gke-cluster: ${{ inputs.gke-cluster }}
      
  deploy:
    needs: setup
    runs-on: ubuntu-latest
          
    steps:
      - name: Get deployment strategy
        run: echo Download deployment strategy

      - name: Run deployment
        run: echo Run strategy - whatever that is

      - name: Run other actions
        run: echo ...
        
  finalize:
    needs: deploy
    uses: ./.github/workflows/finalize_deployment-sample.yml
