name: Deploy GKE

on:
  # This is reusable workflow - providing full GKE deploy
  workflow_call:
    inputs:
      gke-cluster:
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # Later on this can be done in self-hosted runner
    runs-on: ubuntu-latest

    steps:

      - name: Setup deployment SA context
        run: echo Obtain SA

      - name: Get deployment strategy
        run: echo Download deployment strategy

      - name: Run deployment
        run: echo Run strategy (actual deployment, this can be action or workflow)

      - name: Run other actions
        run: echo ...

      - name: Finalize
        run: |
          echo Register deployment status
          echo ...
