name: Full GKE deploy workflow

on:
  workflow_dispatch:
    inputs:
      gke-cluster:
        required: true
        type: string
  # This is reusable workflow - providing full GKE deploy
  workflow_call:
    inputs:
      gke-cluster:
        required: true
        type: string

jobs:
  setup:
    uses: ./.github/workflows/setup_gke_sa-sample.yml
    with: 
      gke-cluster: ${{ inputs.gke-cluster }}
      
  deploy:
    needs: setup
    uses: ./.github/workflows/deploy_gke-sample.yml
        
  finalize:
    needs: deploy
    uses: ./.github/workflows/finalize_deployment-sample.yml
