name: Composite actions use example

on:
  workflow_dispatch:
    inputs:
      gke-cluster:
        required: true
        type: string
  # This is reusable workflow - providing full GKE deploy
  workflow_call:
    inputs:
      gke-cluster:
        required: true
        type: string

jobs:
  run-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Full deploy
        uses: ./.github/actions/deploy-gke
        with: 
          cluster-name: ${{ inputs.gke-cluster }}
