name: Setup GKE deployment SA context

on:
  workflow_call:
    inputs:
      gke-cluster:
        required: true
        type: string

jobs:
  setup-sa:
    runs-on: ubuntu-latest

    steps:

      - name: Setup deployment SA context
        run: echo Obtain SA for ${{ inputs.gke-cluster }}
