name: 'Perform deployment with auth'
description: ''
inputs:
  cluster-name:  
    description: 'Cluster name'
    required: true
runs:
  using: "composite"
  steps:
    - name: Authorize in the cluster
      uses: ./.github/actions/auth-gke
      with:
        cluster-name: ${{ inputs.cluster-name }}
    - name: Do actual deployment
      run: echo Deploying...
      shell: bash
    - name: Finalize deployment
      uses: ./.github/actions/finalize-deploy
